baseURL = "https://3xpl0its.xyz/"
languageCode = "en-gb"
title = "3xpl0its"
theme = "bulma"
summaryLength = 30

# Code syntax
pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

# Pagination
paginate=5

[permalinks]
  blog = "/blog/:year/:month/:title/"

[params]
  favicon = "favicon.jpg"

  # Social
  [[params.social]]
    name = "fas fa-globe"
    url = "https://3xpl0its.xyz"
  [[params.social]]
    name = "fab fa-git"
    url = "https://github.com/jackcoble"
  [[params.social]]
    name = "fab fa-keybase"
    url = "https://keybase.io/jackcoble"
  [[params.social]]
    name = "fas fa-rss"
    url = "https://blog.3xpl0its.xyz/index.xml"
  [[params.social]]
    name = "fab fa-bitcoin"
    url = "/addresses.txt"

  # Navigation
  [[params.navigation]]
    name = "Home"
    url = "/"
  [[params.navigation]]
    name = "Blog"
    url = "/blog"
  [[params.navigation]]
    name = "About"
    url = "/about"
  [[params.navigation]]
    name = "Contact"
    url = "/contact"