baseURL = "https://blog.3xpl0its.xyz/"
languageCode = "en-us"
title = "3xpl0its | Blog"
theme = "hugo-theme-bulma"

# Code syntax
pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

# Pagination
paginate=3

[permalinks]
  posts = "/:year/:month/:title/"

[params]
    mode="dark"
    featherIconsCDN=true