baseURL = "https://blog.3xpl0its.xyz/"
languageCode = "en-gb"
title = "3xpl0its | Blog"
theme = "hugo-theme-bulma"
summaryLength = 30

# Code syntax
pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

# Pagination
paginate=5

[permalinks]
  posts = "/:year/:month/:title/"

[params]
  [[params.social]]
    name = "fas fa-globe"
    url = "https://3xpl0its.xyz"
  [[params.social]]
    name = "fab fa-git"
    url = "https://github.com/jackcoble"
  [[params.social]]
    name = "fab fa-keybase"
    url = "https://keybase.io/jackcoble"
  [[params.social]]
    name = "fas fa-rss"
    url = "https://blog.3xpl0its.xyz/index.xml"