baseURL = "https://coble.uk/"
languageCode = "en-gb"
title = "Jack Coble"

[permalinks]
  blog = "/blog/:year/:month/:title/"

[params]
  favicon = "favicon.jpg"

  # Navigation
  [[params.navigation]]
    name = "Home"
    url = "/"
  [[params.navigation]]
    name = "Blog"
    url = "/blog"
  [[params.navigation]]
    name = "Links"
    url = "/links"
  [[params.navigation]]
    name = "RSS"
    url = "/index.xml"