baseURL = "https://www.3xpl0its.xyz/"
languageCode = "en-us"
title = "3xpl0its.xyz"
theme = "archie"

# Code syntax
pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

# Pagination
paginate=3

[params]
    mode="dark"
    featherIconsCDN=true