baseURL = "https://coble.uk/"
languageCode = "en-gb"
title = "Jack Coble"

theme = "cactus"

[params]
description = "Welcome to my website! This is the place where I write about what I am working on, and everything inbetween! I'm an avid fan of open source software, and like to contribute where I can."

mainSection = "posts"

postsOnHomePage = 5
showAllPostsOnHomePage = false

colortheme = "dark"

projectsUrl = "https://github.com/jackcoble"
showProjectsList = true

rss = true

[[params.social]]
link = "https://github.com/jackcoble"
name = "github"

[[params.social]]
link = "jack@coble.uk"
name = "email"

[[params.social]]
link = "https://keybase.io/jackcoble"
name = "keybase"

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3
