baseURL = "https://3xpl0its.xyz/"
languageCode = "en-gb"
title = "3xpl0its"
theme = "bulma"
summaryLength = 30

# Code syntax
pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

# Pagination
paginate=5

[permalinks]
  blog = "/blog/:year/:month/:title/"

[params]
  favicon = "favicon.jpg"

  # Navigation
  [[params.navigation]]
    name = "Home"
    url = "/"
  [[params.navigation]]
    name = "Blog"
    url = "/blog"
  [[params.navigation]]
    name = "RSS Feed"
    url = "/index.xml"