baseURL = "https://coble.uk/"
languageCode = "en-gb"
title = "Jack Coble"
publishDir = "_site"

theme = "cactus"

[params]
description = "Welcome to my website! This is the place where I write about what I am working on, and everything inbetween! I love to write software and contribute to open source whenever I can!"

mainSection = "posts"

postsOnHomePage = 5
showAllPostsOnHomePage = false

colortheme = "dark"

projectsUrl = "https://github.com/jackcoble"
showProjectsList = true

rss = true

[permalinks]
  posts = "/:year/:month/:day/:title/"

[[params.social]]
link = "https://github.com/jackcoble"
name = "github"

[[params.social]]
link = "jack@coble.uk"
name = "email"

[[params.social]]
link = "https://keybase.io/jackcoble"
name = "keybase"

[[params.social]]
link = "/index.xml"
name = "rss"

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2