baseURL = "https://blog.3xpl0its.xyz/"
languageCode = "en-gb"
title = "3xpl0its | Blog"
theme = "hugo-theme-bulma"
summaryLength = 30

# Code syntax
pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

# Pagination
paginate=5

[permalinks]
  posts = "/:year/:month/:title/"